const { Post } = require('../models');

const postData = [
  {
    title: 'What is Sequelize',
    post_text: 'Sequelize is a promise-based Node.js ORM for Postgres, MySQL, MariaDB, SQLite, and Microsoft SQL Server. Its features are solid transaction support, relations, eager and lazy loading, read replication and many more..',
    user_id: 1,
  },
  {
    title: 'What is Handlebars',
    post_text: 'Handlebars.js is a popular templating engine that is powerful, simple to use and has a large community. It is based on the Mustache template language, but improves it in several important ways. With Handlebars, you can separate the generation of HTML from the rest of your JavaScript and write cleaner code.',
    user_id: 2,
  },
  {
    title: 'What is Handlebars Partials',
    post_text: 'Handlebars allows for template reuse through partials. Partials are normal Handlebars templates that may be called directly by other templates.',
    user_id: 2,
  },
  {
    title: 'What is Sessions',
    post_text: 'In computer programming, session variables store temporary information, sometimes to use for retrieving and viewing data on multiple web pages.',
    user_id: 3,
  },
  {
    title: 'What is Hashing',
    post_text: 'Hashing is simply passing some data through a formula that produces a result, called a hash. That hash is usually a string of characters and the hashes generated by a formula are always the same length, regardless of how much data you feed into it. For example, the MD5 formula always produces 32 character-long hashes.',
    user_id: 4,
  },
  {
    title: 'What is Express.js',
    post_text: 'Express.js is a Node.js framework. Its the most popular framework as of now',
    user_id: 5,
  },
]

const seedPosts = () => Post.bulkCreate(postData);

module.exports = seedPosts;